export type {
  ActivePhrase,
  BoutResult,
  ChatMessage,
  ClientMessage,
  CoachAdvice,
  Corner,
  FightAction,
  FightPhase,
  FighterCard,
  FighterPublic,
  FighterRecord,
  ImpactEvent,
  ImpactResult,
  LobbyStatus,
  MatchState,
  PhraseBeat,
  PhraseBeatInput,
  PhraseMove,
  PhraseStyle,
  ServerMessage,
  ThrowPhraseInput,
} from '../shared/types.ts'
